### ISSUE TITLE
Black screen (no video) at high resolutions than 1080p

### ISSUE THREAD

**Issue by rogerhlg** [TheElixZammuto/moonlight-xbox#154]
Hey fellas, i trying to play some games but no luck... audio/mouse works fine, everything works fine in <= 1080p.. but if i change to 1440p or higher, video stops in a black screen.

** Logs **
https://gist.github.com/rogerhlg/e387924a6f399e3c16a0a5fedbfc48cc

Log from Xbox: 
Audio port: 48000
Video port: 47998
Control port: 47999
Stage 4 completed
done
Initializing control stream...Stage 5 started
Stage 5 completed
done
Initializing video stream...Stage 6 started
Stage 6 completed
done
Initializing input stream...Stage 7 started
Stage 7 completed
done
Starting control stream...Stage 8 started
Stage 8 completed
done
Starting video stream...Stage 9 started
Using H264
Decoding Started
Stage 9 completed
done
Starting audio stream...Stage 10 started
Stage 10 completed
done
Starting input stream...Stage 11 started
Stage 11 completed
done

**Guest Information:**
 - Xbox Model: Xbox series S
 - TV Resolution: 4k

**Host Information**
- Operating System: Windows (I tried in a Ubuntu too, same problem)
- Host Software: Sunshine,
- Monitor Resolutions: 1440p

**Additional context**
Using a android or a other windows works fine too

Anyone could help me? 😭

**Comment by ReenigneArcher** [comment]
What Sunshine version?

**Comment by rogerhlg** [comment]
I tried with the current version and the new pre-release -> v2024.1227.43619

today i could play for like 5minutes in a 1080p > resolution them turn green/black ;/

**Comment by zhang33ya** [comment]
i get same issue on xsx

**Comment by Tydiel** [comment]
I had the same issue. I saw in the Sunshine logs that it was only recognizing the integrated Intel graphics and not my NVIDIA GPU. I realized my monitor was plugged into my motherboard and not my GPU. This fixed it. Worth a sanity check at least.

**Comment by TheElixZammuto** [comment]
Is this fixed with 1.17.5?

**Comment by balgerion** [comment]
Update 30.08 h264 still not working on resolution bigger than 1080p 

I have enough network bandwidth to use h264 for 4k and squeeze some decoding ms but unfortunately still not working here - h265 4k 60 , no issues
