### ISSUE TITLE
No Signal when HDR is enabled

### ISSUE THREAD

**Issue by DeadBread99** [TheElixZammuto/moonlight-xbox#161]
**Describe the bug**
When HDR is enabled on the Moonlight App and the host PC i get no Signal from my TV

**To Reproduce**
1. Go to 'Setting'
2. Click on 'Enable HDR'

**Expected behavior**
My TV should switch to HDR and show Image

**Screenshots or Videos**
If applicable, add screenshots or video recordings to help explain your problem.

** Logs **
While pressing Menu + View and then "Show Logs", are there any relevant log lines?

**Guest Information:**
 - Xbox Model: [Xbox Series X]
 - TV Resolution: [4K,HDR] (LG C1)

**Host Information**
- Operating System: [Windows]
- Host Software: [Sunshine]
- Monitor Resolutions

**Additional context**

**Comment by TheElixZammuto** [comment]
Has this been fixed with version 1.17.0?

**Comment by funhardin** [comment]
I can confirm the issue still exists, though I think this might just be an incompatible issue. The TV doesn't switch HDR or VRR on without Dolby Vision triggering (well, I think anyway). The moonlight app is sending an HDR signal to the TV, but it isn't switching over to a compatible mode (hence the no signal). I have no idea what to provide but willing to help as best as I can.

**Comment by TheElixZammuto** [comment]
Should be fixed by 1.17.5
