### ISSUE TITLE
The stream is stuttering

### ISSUE THREAD

**Issue by Nun-z** [TheElixZammuto/moonlight-xbox#2]
Here's another issue in case you were not aware of it.  I'm getting stuttering with the stream, best described in the video here about 15 seconds in: https://streamable.com/0v1nqv

**Comment by Nun-z** [comment]
By the way, is it ok that I forked your repo and made some changes?  If not, I can delete the fork.

**Comment by TheElixZammuto** [comment]
Hi, at the moment I'm still trying the best way to fix the stuttering issue (I'm trying to implement a frame queue for that matter)

As for the license, I forgot to add it, but since the upstream dependencies are available on GPLv3, my only choice of license is this one, so feel free to do anything in the limits of GPL3 

The only thing I ask is for the moment to not upload the app onto the Microsoft Store accessible publicly by users, the app is still in a very early stage and it would not give a good experience for them. If and when the application will be ready for releasing, I'll be more than happy to upload it to the Microsoft store myself (or someone else from the Moonlight Community)

**Comment by Nun-z** [comment]
That works, thanks.  Any uploads will be private and accessible only to me.

**Comment by Nun-z** [comment]
I've recorded the frame-pacer and non-frame-pacer performances, and the videos are below:

1.  30 FPS no frame-pacer: https://streamable.com/wnskxe
2.  30 FPS frame-pacer: https://streamable.com/sg0jih
3.  60 FPS no frame-pacer: https://streamable.com/d1333l
4.  60 FPS frame-pacer: https://streamable.com/n1dtoc

It looks like the stream isn't as smooth with the frame-pacer build.

**Comment by TheElixZammuto** [comment]
Seems that the app wrongly changed the render frame index even when the app should not. I have updated the branch to fix this and I also added some changes to reduce the queue index if we are going too far between frames

**Comment by Nun-z** [comment]
1.  30 FPS frame-pacer performance: https://streamable.com/5qw5tz
2.  60 FPS frame-pacer performance: https://streamable.com/xm2mmg

**Comment by TheElixZammuto** [comment]
I have updated the branch some more. In the tests I did on Xbox One seems that the problem of skipped/jumped frame is almost elimiated, but I would also like your Feedback

**Comment by Nun-z** [comment]
The issue seems much improved.  I didn't notice any stutters with 30 FPS over a 1.5 hour session, and there were only minor issues with 60 FPS, though that may be a different issue.  

Here's footage of 60 FPS: https://vimeo.com/607043093

**Comment by TheElixZammuto** [comment]
Thank you, I think the issue probably is within the part of the code that skips frame if Rendering runs too behind over the decoder (to avoid audio and input desync). Probably the frame skipping is too abrupt

**Comment by TheElixZammuto** [comment]
I pushed v1.6.2 that should improve smoothness in streaming

**Comment by Nun-z** [comment]
I think I may be seeing some regression on this issue.  At 30 FPS, I got stuttering 9 minutes in, necessitating restarting the client.  I then had stuttering again 3 minutes later.  60 FPS is showing extreme input lag, and is more or less unplayable.

I'm going to test again with this repository to make sure this isn't due to something I changed.

**Comment by Nun-z** [comment]
I was testing on release, but the debug configuration tells a different story.  Although 60 FPS still has occasional spikes of input lag, I didn't notice any stuttering at 30 or 60 FPS on the debug configuration.  Sometimes the stream freezes, however, requiring pressing the home button and then re-opening the app to fix.

**Comment by TheElixZammuto** [comment]
Hi, I did some more changes that exposed some params for the rendering time, FPS and such. I also re-enabled the frame jumper, hoping it does not break anything. Are you able to give me how  the params during streaming changes? Thank you in advance!

**Comment by Nun-z** [comment]
The average rendering time starts around 30 ms and slowly ticks up over time.  If I let it run for a while, it eventually crosses 100 ms and just keeps increasing.  The renderer FPS is volatile but generally seems to be around 430 FPS, but sometimes it drops to around 300 FPS.  The decoder FPS is steady around 59 FPS.  Frame lag is fixed at 0, though once in a while I saw it briefly increase to 1 before returning to 0.

During a brief freeze (just a few seconds), I noticed a change in the logs (see here: https://i.imgur.com/QRNPgvh.png).  The stream froze more significantly several times, and each of those times time the stats were updated but the stream never stopped being frozen.  Here are images of the logs from the freezes I experienced: https://i.imgur.com/TPKLwHI.png, https://i.imgur.com/3w22ljc.png, https://i.imgur.com/4eiDHOf.png.

**Comment by Nun-z** [comment]
I do think that it is playable apart from the freezes.  I'm not seeing any input lag at this point, and the stream is smooth at 60 FPS and tolerable at 30 FPS.

**Comment by TheElixZammuto** [comment]
Hi, I have fixed the calculation. you were right, I forgot to reset the counter on each second

I also made some other changes and on my tests it seems that the freezing issue seems resolved, are you able to confirm this to me?

**Comment by TheElixZammuto** [comment]
Just noticed that I didn't commit a change for enabling Vsync 😅

**Comment by Nun-z** [comment]
No worries.  However, I am still getting freezing with this update, and there's also now a lot of stuttering.  See this video for a rough example: https://streamable.com/gwotrw.

**Comment by TheElixZammuto** [comment]
Does release 1.8.2 with Frame Pacer Imprevement improve things?

https://github.com/TheElixZammuto/moonlight-xbox/releases/tag/1.8.2-pacer

**Comment by Nun-z** [comment]
The issue does seem to be improved from when I last tested it, but the stuttering is still present.  See this video: https://streamable.com/01050l

**Comment by TheElixZammuto** [comment]
Any improvements with release 1.8.5?

https://github.com/TheElixZammuto/moonlight-xbox/releases/tag/1.8.5

**Comment by Nun-z** [comment]
With this release, I am still getting stuttering similar to what was in the previous video, but it appears to be more subtle.  I am also getting freezes that require restarting the stream to fix, and these freezes appear to happen pretty frequently.

Here's a video showing the stuttering I'm getting: https://streamable.com/

Here's a video showcasing the frequency of the freezes: https://streamable.com/u52498

**Comment by ReenigneArcher** [comment]
Same issue in 1.8.3.70 (retail mode). Occurs no matter what resolution or FPS is set.

**Comment by TheElixZammuto** [comment]
Any changes now with version 1.8.8? I made the pacer more robust by checking the actual mutex status befor switching frames

**Comment by Nun-z** [comment]
With 60 FPS, I got a freeze at the 4 minute mark, and then more freezes every 5-10 minutes, which required restarting the app to fix. With 30 FPS the freezes happened more often, sometimes within 30 seconds of restarting the stream, which largely prevented further testing. Attempts to test at 120 FPS resulted in a status 10060 error message and a green screen.   

However, I didn't notice any stuttering at 60 FPS (over a 45-minute session) or at 30 FPS. Changing the resolution to 1080p results in a green screen and then a crash at 30 FPS, 60 FPS, and 120 FPS.

**Comment by TheElixZammuto** [comment]
I'm glad that in your tests there are no stutters, hopefully we are getting closer.
Anyway, is there any strange message inside the application logs when the application is freezing? (Menu + View -> Show Logs)

**Comment by Nun-z** [comment]
I'm seeing a lot of "invalidate reference frame request sent," and eventually it just keeps repeating "input queue reached maximum size limit."  I'm going to try again tomorrow and I'll edit this if I find something more specific.

**Comment by TheElixZammuto** [comment]
According to PR #26 (which was merged), this build should improve the performance of your issue : https://github.com/TheElixZammuto/moonlight-xbox/suites/5533890570/artifacts/177901227

**Comment by Nun-z** [comment]
I'll test it within the next few days.  Hopefully this is all sorted out.

**Comment by MichaelMKenny** [comment]
> I'll test it within the next few days. Hopefully this is all sorted out.
> 
> Edit: Sorry. It's not fixed. I got stuttering and then a freeze within 7 minutes (with the audio still continuing). Note that this issue does not occur under the exact same network conditions and with the exact same host when using, for example, an Android Moonlight client.

What bitrate are using? I got the stuttering and freezing after a while at bitrates over 20mbps. But when I’d go as low as 20mbps, I would get the laggy stream. That’s what I fixed in the pull request. So if you set it 20mbps, you won’t get high latency, and also won’t get the freezing/stuttering. 

Hope that helps.

**Comment by Nun-z** [comment]
See here: https://streamable.com/7mu67c.  Results at 20 Mbps were identical to the shown 8 Mbps.

**Comment by MichaelMKenny** [comment]
> See here: https://streamable.com/7mu67c. Results at 20 Mbps were identical to the shown results at 8 Mbps.

Darn. All I know is that I tried to fix the high latency issue. 

Someone has to hunt down the freezing bug. In my testing it didn’t happen at 20mbps. Probably differs based on setup.

Thanks for testing though :)

**Comment by Nun-z** [comment]
What is your internet speed?  Mine may be a bit slow, 15.66 Mbps down and 15.53 Mbps up.

**Comment by TheElixZammuto** [comment]
Any changes with this build? https://github.com/TheElixZammuto/moonlight-xbox/suites/5598764010/artifacts/181751916

**Comment by Nun-z** [comment]
Sorry, not as far as I can see.

**Comment by TheElixZammuto** [comment]
I have refactored the renderer, using a frame pull approach instead of a push one. This eliminates all the multithread code and simplifies the implementation.

It's still a bit glitchy, so a couple tries would be needed to make the connection work, but I would like to have some early feedback on this, thank you!

https://github.com/TheElixZammuto/moonlight-xbox/suites/6582126521/artifacts/246693976

**Comment by Nun-z** [comment]
I could only coax it into working at 1280x720 (any other resolution causes it to crash), but I didn't notice any stuttering or freezing over an hour session.

**Comment by TheElixZammuto** [comment]
> I could only coax it into working at 1280x720 (any other resolution causes it to crash), but I didn't notice any stuttering or freezing over an hour session. My network situation has changed for the better, however, so the conditions are not the same.

I don't know if it's for the network, the refactor, or both. In any case, it's better :^)

With this build I've fixed some crashes when an IDR frame is needed: https://github.com/TheElixZammuto/moonlight-xbox/suites/6596489223/artifacts/247623948

If it does work I'll publish it on Retail and close (finally *hehe* ) the issue

**Comment by Nun-z** [comment]
720p looks great, no crashes or stuttering during an hour session.  1080p crashes immediately, but either way, this bug is no longer present on my end.

**Comment by TheElixZammuto** [comment]
> 720p looks great, no crashes or stuttering during an hour session. 1080p crashes immediately, but either way, this bug is no longer present on my end.

Gotcha, let me know if you can send me a crash dump so I can check this out

**Comment by Nun-z** [comment]
Here's a crash log from trying to launch a stream at 1080p: https://mega.nz/file/3cgUTKLB#OAxQqBa0SnehekQ2VD0FtYKmBkdMyBslWlbaYd790A8

**Comment by TheElixZammuto** [comment]
I wasn't able to open the pdb file, I'm not sure why, one reason it can be due to the different package name but I'm not sure unfortunately

**Comment by Nun-z** [comment]
Sorry about that.  I can open the file on my end using Visual Studio.  The exception is thrown in client.h on line 472.  It's a read access violation and it says that "device.ptr_ was nullptr."  The call stack starts at line 67 of moonlight_xbox_dxMain.cpp.

**Comment by TheElixZammuto** [comment]
> Sorry about that. I can open the file on my end. The exception is thrown in client.h on line 472. It's a read access violation and it says that "device.ptr_ was nullptr." The call stack starts at line 67 of moonlight_xbox_dxMain.cpp.

Are you able to give me the entiere stacktrace?

**Comment by Nun-z** [comment]
No need for the stack trace.  The build you just linked me to works with 1080p.

**Comment by TheElixZammuto** [comment]
Perfect, I can now close this issue!
