### ISSUE TITLE
Two Controller causes input lag: "Input queue reached maximum size limit", version 1.17.8

### ISSUE THREAD

**Issue by csetom** [TheElixZammuto/moonlight-xbox#217]
**Describe the bug**

Since version  1.17.8, with two controller connected, the logs starts to fill with "input queue reached maximum size limit". The games input start to delay, and the game is unplayable. 

**To Reproduce**

1. Start Moonlight (version: 1.17.80.70)
2. Open logs
3. Connect second controller
4. Now you can see the logs are filled with "input queue reached maximum size limit".
5. Try playing a coop game, like Baldurs Gate 3. The input delay starts getting worse and worse, even in the menu. 

**Expected behavior**
No problem. 

**Screenshots or Videos**
None. 

** Logs **
Input queue reached maximum size limit.

**Guest Information:**
 - Xbox Model:  Xbox Series S
 - TV Resolution: 4K HDR

**Host Information**
- Operating System: Windows
- Host Software: Sunshine
- Monitor Resolutions: 4K Virtual Display

**Additional context**
This is similar similar error to this issue: https://github.com/TheElixZammuto/moonlight-xbox/issues/105.

**Comment by Lang01000001** [comment]
Also experiencing this issue with 2 controllers. Works fine with one controller but if I connect a second it causes massive input delay. Checking the logs I also see "input queue reached maximum size limit" errors every second or so. If I turn off one controller or switch to mouse mode, the input lag goes away and the log doesn't record more errors. I tried restarting both devices, changing config settings in both sunshine and moonlight, turning off steam input for controllers and nothing seems to make it noticeably better. This only started happening within the past few days and I haven't noticed this issue before.

OS: Windows
GPU: AMD RX 6700 XT 
Monitor Resolution: 1080

Xbox Series X

**Comment by j-scrizz** [comment]
https://github.com/TheElixZammuto/moonlight-xbox/issues/105
It seems it has come back!

@TheElixZammuto - can you remember how you fixed this?

**Comment by marcgeerlings7** [comment]
Also experiencing this issue, xbox series s. No problems with one controller.

**Comment by funkmaster-dan** [comment]
Also experiencing this big exactly as described on Xbox Series X.

**Comment by andygrundman** [comment]
Yeah I think I see the problem, the Xbox input code doesn't work properly when controllers are idle, and sends hundreds of updates per second to the server per controller basically all the time. Other clients only send data when there is activity. So some timing code I changed was ok with 1 controller but 2 controllers exceeds the rate limit.

**Comment by cgutman** [comment]
The problem is that the interleaved duplicative input from multiple controllers that the Xbox client is sending is a pathological case for the gamepad batching code in moonlight-common-c because it's only capable of batching with the next queued packet in the input queue (which will never be from the same controller in this interleaved polling case).

https://github.com/moonlight-stream/moonlight-common-c/commit/e59a5f5b5384b11b5de063fc4dc6e17307f9eedc rewrites the batching code to fix this (though you should still try to avoid sending useless controller updates).

**Comment by RetroMan99** [comment]
Are there any updates regarding this? I am having the same problem. Moonlight works great playing solo (with own controller), but as soon as a second controller is added the input lag is atrocious and non-playable. 

I'm really thankful for the 120hz fix in the latest update, but this issue with two controllers is quite frustrating too. Any way we can help out the dev somehow?

**Comment by RobWaterhouse95** [comment]
Can confirm that the issue immediately goes away when you disconnect controllers and leave only one connected.

I guess the PR and the moonlight-common-c are options to fix this issue, but what about reverting the recent changes that brought the bug?

**Comment by eltentacle** [comment]
Same problem here. Logitech Adaptive Controller + regular Xbox controller as co-pilot. Worked fine before the patch, now huge input delay and the log keeps saying “input queue reached maximum size limit” nonstop.

**Comment by csetom** [comment]
Why is this closed? The issue is still there, and there is no new version of the application.

**Comment by TheElixZammuto** [comment]
> Why is this closed? The issue is still there, and there is no new version of the application.

Github decided to closed since I merged the the linked pull request
I've put up v1.17.8 for dev mode if you want to test the fix https://github.com/TheElixZammuto/moonlight-xbox/releases/tag/1.17.8

**Comment by GoD-Tony** [comment]
If you're anxiously waiting for an update to the retail app (which can take days even if published today), you can also test the fix on the server side by updating Sunshine to a development build.

Select the latest commit at the top and then scroll all the way down to Artifacts: https://github.com/LizardByte/Sunshine/actions/workflows/ci.yml?query=branch%3Amaster

**Comment by andygrundman** [comment]
> If you're anxiously waiting for an update to the retail app (which can take days even if published today), you can also test the fix on the server side by updating Sunshine to a development build.

I'm not sure what you mean, this is a client-side bug.

**Comment by GoD-Tony** [comment]
> I'm not sure what you mean, this is a client-side bug.

See https://github.com/TheElixZammuto/moonlight-xbox/issues/217#issuecomment-3508871730

With the change mentioned above, Sunshine should be able to handle the excess inputs sent from the Xbox client.

**Comment by andygrundman** [comment]
> > I'm not sure what you mean, this is a client-side bug.
> 
> See [#217 (comment)](https://github.com/TheElixZammuto/moonlight-xbox/issues/217#issuecomment-3508871730)
> 
> With the change mentioned above, Sunshine should be able to handle the excess inputs sent from the Xbox client.

It's neither here nor there because I already fixed the issue, but I think you misunderstood Cameron's change, which was also to the client-side but just one layer up in the Limelight API. I have bumped m-c-c in my current Xbox PR so that change will get pulled in too.

**Comment by RobWaterhouse95** [comment]
Is there anyway for a regular user to test the fix on their xbox? As far as I understand you need a developer account to do so?

Alternatively, can I request the process of this being promoted begins, please, as the bug is actively affecting users.

**Comment by eltentacle** [comment]
Tried with Sunshine 2025.1122.185837 but the problem persists. Lag when playing with two controllers and "input queue reached maximum size limit" over and over.

> If you're anxiously waiting for an update to the retail app (which can take days even if published today), you can also test the fix on the server side by updating Sunshine to a development build.
> 
> Select the latest commit at the top and then scroll all the way down to Artifacts: https://github.com/LizardByte/Sunshine/actions/workflows/ci.yml?query=branch%3Amaster

**Comment by andygrundman** [comment]
> Is there anyway for a regular user to test the fix on their xbox? As far as I understand you need a developer account to do so?

Anyone can test dev builds, the only cost is some initial setup time and hoop jumping. I posted about this on [Reddit](https://www.reddit.com/r/MoonlightStreaming/comments/1p2qhrt/moonlight_for_xbox_11710pre1_dev_build_for_testing/).

**Comment by RobWaterhouse95** [comment]
I am testing this on 1.17.10 and can confirm the latency issue has been resolved. Thank you very much for sorting this.

However, I am now seeing a lot of tearing issues which I will raise on another issue.
